/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentRefRouteImport } from './routes/payment/$ref'
import { Route as PayAddressRouteImport } from './routes/pay/$address'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRefRoute = PaymentRefRouteImport.update({
  id: '/payment/$ref',
  path: '/payment/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const PayAddressRoute = PayAddressRouteImport.update({
  id: '/pay/$address',
  path: '/pay/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/pay/$address': typeof PayAddressRoute
  '/payment/$ref': typeof PaymentRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/pay/$address': typeof PayAddressRoute
  '/payment/$ref': typeof PaymentRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/pay/$address': typeof PayAddressRoute
  '/payment/$ref': typeof PaymentRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/onboarding'
    | '/scan'
    | '/send'
    | '/settings'
    | '/pay/$address'
    | '/payment/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/onboarding'
    | '/scan'
    | '/send'
    | '/settings'
    | '/pay/$address'
    | '/payment/$ref'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/onboarding'
    | '/scan'
    | '/send'
    | '/settings'
    | '/pay/$address'
    | '/payment/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  OnboardingRoute: typeof OnboardingRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  PayAddressRoute: typeof PayAddressRoute
  PaymentRefRoute: typeof PaymentRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$ref': {
      id: '/payment/$ref'
      path: '/payment/$ref'
      fullPath: '/payment/$ref'
      preLoaderRoute: typeof PaymentRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$address': {
      id: '/pay/$address'
      path: '/pay/$address'
      fullPath: '/pay/$address'
      preLoaderRoute: typeof PayAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  OnboardingRoute: OnboardingRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  PayAddressRoute: PayAddressRoute,
  PaymentRefRoute: PaymentRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
