/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentsIndexRouteImport } from './routes/payments/index'
import { Route as MerchantsIndexRouteImport } from './routes/merchants/index'
import { Route as PaymentsNewRouteImport } from './routes/payments/new'
import { Route as MerchantsNewRouteImport } from './routes/merchants/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsIndexRoute = MerchantsIndexRouteImport.update({
  id: '/merchants/',
  path: '/merchants/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsNewRoute = PaymentsNewRouteImport.update({
  id: '/payments/new',
  path: '/payments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsNewRoute = MerchantsNewRouteImport.update({
  id: '/merchants/new',
  path: '/merchants/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchants/new': typeof MerchantsNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchants/new': typeof MerchantsNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/merchants': typeof MerchantsIndexRoute
  '/payments': typeof PaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchants/new': typeof MerchantsNewRoute
  '/payments/new': typeof PaymentsNewRoute
  '/merchants/': typeof MerchantsIndexRoute
  '/payments/': typeof PaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchants/new'
    | '/payments/new'
    | '/merchants/'
    | '/payments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/merchants/new' | '/payments/new' | '/merchants' | '/payments'
  id:
    | '__root__'
    | '/'
    | '/merchants/new'
    | '/payments/new'
    | '/merchants/'
    | '/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantsNewRoute: typeof MerchantsNewRoute
  PaymentsNewRoute: typeof PaymentsNewRoute
  MerchantsIndexRoute: typeof MerchantsIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/': {
      id: '/merchants/'
      path: '/merchants'
      fullPath: '/merchants/'
      preLoaderRoute: typeof MerchantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/new': {
      id: '/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof PaymentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/new': {
      id: '/merchants/new'
      path: '/merchants/new'
      fullPath: '/merchants/new'
      preLoaderRoute: typeof MerchantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantsNewRoute: MerchantsNewRoute,
  PaymentsNewRoute: PaymentsNewRoute,
  MerchantsIndexRoute: MerchantsIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
